docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - Intro: intro.md
    - ClassFileLocator: class-file-locator.md
site_name: laminas-file
site_description: laminas-file
repo_url: 'https://github.com/laminas/laminas-file'
